### ISSUE TITLE
Missing rescaling in SGD method?

### ISSUE THREAD

**Issue by csherstan** [Cranial-XIX/CAGrad#1]
https://github.com/Cranial-XIX/CAGrad/blob/23ff27ffe3ac37a00c3738822049740e8e942d86/mtrl/mtrl_files/cagrad.py#L225

In your SGD method `cagrad` you divide by `scale`, but do not multiply by `scale` at https://github.com/Cranial-XIX/CAGrad/blob/23ff27ffe3ac37a00c3738822049740e8e942d86/mtrl/mtrl_files/cagrad.py#L254

I notice in your other two methods that you rescale before returning the gradient. Is this an error in the SGD method?

**Comment by Cranial-XIX** [comment]
Hi, sorry for the confusion. But in https://github.com/Cranial-XIX/CAGrad/blob/23ff27ffe3ac37a00c3738822049740e8e942d86/mtrl/mtrl_files/cagrad.py#L254
note that it is multiplied by `grads = grad_vec`, which are the original gradients (not normalized). But in `cagrad_exact` and `cagrad_fast`, the final update vector is first calculated using the normalized gradients, so we scale it back.

**Comment by csherstan** [comment]
Ah, thank you for the clarification.
