### ISSUE TITLE
The NYU-V2 datasets

### ISSUE THREAD

**Issue by SYVAE** [Cranial-XIX/CAGrad#3]
The link of the NYU-V2 cannot be found?

**Comment by Cranial-XIX** [comment]
I can see the dropbox link, could you please try again?

**Comment by SYVAE** [comment]
I am very interested in your work: "cagrad". Thanks for your help, but I can't still open this link. I will be very grateful if you can upload it onto the google-drive.

**Comment by Cranial-XIX** [comment]
Thanks for your interest! I uploaded the dataset to a google drive [link](https://drive.google.com/file/d/1n15Uf-rqtx-LFohcwRkq3HBF-jQvsY1-/view?usp=sharing) and hope it works for you. On the other hand the original dropbox link is working on my side. I think there might be some issue with your dropbox access.

**Comment by Cranial-XIX** [comment]
I am closing this issue. If you have further questions feel free to reopen it :)
