### ISSUE TITLE
About Multi Fashion+MNIST experiment

### ISSUE THREAD

**Issue by tuantran23012000** [Cranial-XIX/CAGrad#6]
Can you provide MNIST experiment, which relate to model architecture? Cause, I used LeNet architecture but can't obtain performance as your result in Figure 4 in your paper.

**Comment by Cranial-XIX** [comment]
Unfortunately, I no longer have the results for the CAGrad. However I have open-sourced some new benchmarks for multitask learning. Please refer to [FAMO](https://github.com/Cranial-XIX/FAMO).
