### ISSUE TITLE
The norm of $g_0$ seems to be incorrect

### ISSUE THREAD

**Issue by PierreQuinton** [Cranial-XIX/CAGrad#7]
The code given here say that $\| g_0\|$ is the mean of the gramian matrix. Would it be possible to know what code was run for the plots of the paper ?

https://github.com/Cranial-XIX/CAGrad/blob/dc3d48152b6196945cfd56144879b9d42353b095/nyuv2/utils.py#L379

**Comment by Cranial-XIX** [comment]
It is correct in the sense that $GG$ is the matrix such that its $GG_{i,j} = g_i^\top g_j$, note it is not the gradient w.r.t inputs but w.r.t parameters. Then we can see that $||g_0||^2 = || (\frac{1}{K} \sum_{i} g_i)^\top (\frac{1}{K} \sum_{j} g_j) ||^2$. By expanding the product on the right you get what the code writes.

**Comment by PierreQuinton** [comment]
Oh I thought it was of shape `[n_losses, n_losses]`, my bad.
